'use client';
import {useEffect,useState} from 'react';
type F={id:string,operateur:string,categorie:string,nom:string,prixFcfa:number,validite:string|null,syntaxe:string,actif:boolean,statutVerification:string,typeSyntaxe:string};
export default function CatalogueClient(){const [rows,setRows]=useState<F[]>([]);const [q,setQ]=useState('');const [op,setOp]=useState('');const [editing,setEditing]=useState<F|null>(null); const [busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/forfaits?'+new URLSearchParams({q,operateur:op}));if(r.status===401)location.href='/connexion';else setRows(await r.json())}useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t)},[q,op]);
 async function save(){if(!editing)return;setBusy(true);const r=await fetch('/api/forfaits/'+editing.id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(editing)});setBusy(false);if(r.ok){setEditing(null);load()}else alert((await r.json()).message||'Erreur')}
 return <main className="max-w-7xl mx-auto p-5 md:p-8 space-y-6"><header><a href="/dashboard" className="muted text-sm">← Dashboard</a><h1 className="text-3xl font-bold mt-2">Catalogue</h1><p className="muted mt-1">Source unique de vérité des forfaits et syntaxes.</p></header><section className="card p-4 flex gap-3"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher un forfait…" className="flex-1 rounded-xl bg-slate-950 border border-slate-700 px-4 py-3"/><select value={op} onChange={e=>setOp(e.target.value)} className="rounded-xl bg-slate-950 border border-slate-700 px-4"><option value="">Tous</option><option value="orange">Orange</option><option value="moov">Moov</option><option value="mtn">MTN</option></select></section><section className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left muted"><th className="p-3">Opérateur</th><th>Catégorie</th><th>Forfait</th><th>Prix</th><th>Syntaxe</th><th>Statut</th><th/></tr></thead><tbody>{rows.map(f=><tr key={f.id} className="border-t border-slate-800"><td className="p-3">{f.operateur}</td><td>{f.categorie}</td><td>{f.nom}</td><td>{f.prixFcfa.toLocaleString('fr-FR')} F</td><td className="font-mono max-w-xs truncate">{f.syntaxe}</td><td>{f.actif?'actif':'inactif'} · {f.statutVerification}</td><td><button onClick={()=>setEditing(f)} className="border border-slate-700 rounded-lg px-3 py-1">Modifier</button></td></tr>)}</tbody></table></div></section>
 {editing&&<div className="fixed inset-0 bg-black/70 p-5 flex items-center justify-center"><div className="card p-6 w-full max-w-xl space-y-3"><div className="flex justify-between"><h2 className="font-bold text-xl">Modifier le forfait</h2><button onClick={()=>setEditing(null)}>✕</button></div>{[['nom','Nom'],['categorie','Catégorie'],['prixFcfa','Prix FCFA'],['validite','Validité'],['typeSyntaxe','Type syntaxe'],['syntaxe','Syntaxe']].map(([k,l])=><label className="block" key={k}><span className="muted text-sm">{l}</span><input value={(editing as any)[k]??''} onChange={e=>setEditing({...editing,[k]:k==='prixFcfa'?Number(e.target.value):e.target.value})} className="w-full mt-1 rounded-xl bg-slate-950 border border-slate-700 px-3 py-2"/></label>)}<label className="flex gap-2"><input type="checkbox" checked={editing.actif} onChange={e=>setEditing({...editing,actif:e.target.checked})}/> Actif</label><select value={editing.statutVerification} onChange={e=>setEditing({...editing,statutVerification:e.target.value})} className="w-full rounded-xl bg-slate-950 border border-slate-700 p-2"><option value="a_tester">À tester</option><option value="verifie">Vérifié</option></select><div className="flex justify-end gap-2"><button onClick={()=>setEditing(null)} className="border border-slate-700 rounded-xl px-4 py-2">Annuler</button><button disabled={busy} onClick={save} className="rounded-xl px-4 py-2 bg-sky-500 text-slate-950 font-semibold">{busy?'Enregistrement…':'Enregistrer'}</button></div></div></div>}
 </main>}
