'use client';
import {useEffect,useState} from 'react';

type Summary={attente_paiement:number,attente_ussd:number,en_cours:number,termine:number,echec:number,traitement_manuel:number};
type Device={id:string,nom:string,operateur:string,statut:string,derniereActivite:string|null,silencieux:boolean};
type Order={id:string,reference:string,operateur:string,numeroMasque:string,montantFcfa:number,etat:string,forfait:{nom:string},dateCreation:string};
type Account={id:string,famille:string,actif:boolean,dateCreation:string,dateDerniereConnexion:string|null};
type Wave={id:string,identifiantExterne:string,reference:string,montantFcfa:number,dateReception:string,rapprochee:boolean};
type WaveData={marchands:{id:string,nom:string,reference:string,actif:boolean}[],nonRapprochees:Wave[]};
type Maintenance={etat:string,sauvegarde:{derniere:string|null,statut:string,prochaine:string|null},message:string};
const money=(n:number)=>`${n.toLocaleString('fr-FR')} F`;
const dt=(s:string|null)=>s?new Date(s).toLocaleString('fr-FR'):'—';
const stateLabel=(s:string)=>s.replaceAll('_',' ');

export default function DashboardClient(){
 const [summary,setSummary]=useState<Summary|null>(null),[devices,setDevices]=useState<Device[]>([]),[orders,setOrders]=useState<Order[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[accountSummary,setAccountSummary]=useState({actifs:0,desactives:0,revoques:0}),[manual,setManual]=useState<Order[]>([]),[wave,setWave]=useState<WaveData>({marchands:[],nonRapprochees:[]}),[maintenance,setMaintenance]=useState<Maintenance|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){
  try{
   const rs=await Promise.all([fetch('/api/dashboard/summary'),fetch('/api/appareils'),fetch('/api/commandes?limit=20'),fetch('/api/comptes'),fetch('/api/comptes/summary'),fetch('/api/commandes?limit=20&etat=traitement_manuel'),fetch('/api/marchands-wave'),fetch('/api/maintenance/status')]);
   if(rs.some(r=>r.status===401)){location.href='/connexion';return}
   const [a,b,c,d,e,f,g,h]=await Promise.all(rs.map(r=>r.json()));
   setSummary(a);setDevices(b);setOrders(c.items||[]);setAccounts(d);setAccountSummary(e);setManual(f.items||[]);setWave(g);setMaintenance(h);setError('');
  }catch{setError('Impossible de rafraîchir le dashboard.');}finally{setLoading(false)}
 }
 useEffect(()=>{load();const id=setInterval(load,15000);return()=>clearInterval(id)},[]);
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});location.href='/connexion'}
 async function toggleAccount(a:Account){const r=await fetch(`/api/comptes/${a.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({actif:!a.actif})});if(r.ok)load();else alert((await r.json()).message||'Modification refusée')}
 async function closeManual(id:string,decision:'EXECUTED_MANUALLY'|'REFUNDED'){if(!confirm(decision==='REFUNDED'?'Confirmer le remboursement manuel ?':'Confirmer que la commande a été exécutée manuellement ?'))return;const r=await fetch(`/api/commandes/${id}/manual`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision})});if(!r.ok)alert((await r.json()).message||'Action refusée');else load()}
 return <main className="max-w-7xl mx-auto p-5 md:p-8 space-y-6">
  <header className="flex flex-col md:flex-row gap-4 justify-between md:items-center"><div><p className="text-sky-400 text-sm font-semibold">DP DIGITAL</p><h1 className="text-3xl font-bold">Dashboard de supervision</h1><p className="muted text-sm mt-1">Une seule page · rafraîchissement automatique toutes les 15 s</p></div><div className="flex gap-2"><a href="/catalogue" className="border border-slate-700 rounded-xl px-4 py-2">Catalogue</a><button onClick={logout} className="border border-slate-700 rounded-xl px-4 py-2">Déconnexion</button></div></header>
  {error&&<div className="rounded-xl border border-red-900 bg-red-950/30 p-3 text-red-200">{error}</div>}
  <section><h2 className="font-bold text-xl mb-3">1 · Résumé du jour</h2><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">{['attente_paiement','attente_ussd','en_cours','termine','echec','traitement_manuel'].map(k=><div className="card p-4" key={k}><p className="muted text-xs uppercase">{stateLabel(k)}</p><p className="text-2xl font-bold mt-2">{summary?.[k as keyof Summary]??'—'}</p></div>)}</div></section>
  <section className="card p-5"><h2 className="font-bold text-xl">2 · Supervision appareils</h2><div className="grid md:grid-cols-3 gap-3 mt-4">{devices.length?devices.map(d=><div className="rounded-xl bg-slate-950/60 border border-slate-800 p-4" key={d.id}><div className="flex justify-between gap-2"><b>{d.nom}</b><span className="text-sm">{d.silencieux?'⚠ silencieux':d.statut}</span></div><p className="muted text-sm mt-2">{d.operateur} · dernier heartbeat : {dt(d.derniereActivite)}</p></div>):<p className="muted">Aucun appareil.</p>}</div></section>
  <section className="card p-5"><div className="flex justify-between gap-3"><h2 className="font-bold text-xl">3 · Commandes</h2><span className="muted text-sm">{loading?'Chargement…':'20 dernières'}</span></div><div className="overflow-x-auto mt-4"><table className="w-full text-sm"><thead><tr className="text-left muted"><th className="p-2">Référence</th><th>Opérateur</th><th>Forfait</th><th>Numéro</th><th>Montant</th><th>État</th><th>Date</th></tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-t border-slate-800"><td className="p-2 font-mono">{o.reference}</td><td>{o.operateur}</td><td>{o.forfait.nom}</td><td>{o.numeroMasque}</td><td>{money(o.montantFcfa)}</td><td>{stateLabel(o.etat)}</td><td>{dt(o.dateCreation)}</td></tr>)}</tbody></table></div></section>
  <section className="card p-5"><h2 className="font-bold text-xl">4 · Comptes</h2><div className="grid grid-cols-3 gap-3 mt-4"><div className="rounded-xl bg-slate-950/60 p-3">Actifs <b>{accountSummary.actifs}</b></div><div className="rounded-xl bg-slate-950/60 p-3">Désactivés <b>{accountSummary.desactives}</b></div><div className="rounded-xl bg-slate-950/60 p-3">Sessions révoquées <b>{accountSummary.revoques}</b></div></div><div className="overflow-x-auto mt-4"><table className="w-full text-sm"><thead><tr className="text-left muted"><th className="p-2">Famille</th><th>Statut</th><th>Dernière connexion</th><th></th></tr></thead><tbody>{accounts.map(a=><tr className="border-t border-slate-800" key={a.id}><td className="p-2">{a.famille}</td><td>{a.actif?'actif':'désactivé'}</td><td>{dt(a.dateDerniereConnexion)}</td><td><button onClick={()=>toggleAccount(a)} className="border border-slate-700 rounded-lg px-3 py-1">{a.actif?'Désactiver':'Activer'}</button></td></tr>)}</tbody></table></div></section>
  <section className="card p-5"><div className="flex justify-between"><h2 className="font-bold text-xl">5 · Traitement manuel</h2><span className="rounded-full bg-amber-900/40 px-3 py-1 text-sm">{manual.length} en attente</span></div>{manual.length?<div className="space-y-3 mt-4">{manual.map(o=><div className="rounded-xl border border-amber-900/50 p-4" key={o.id}><div className="flex flex-col md:flex-row gap-3 md:justify-between"><div><b>{o.reference}</b><p className="muted text-sm">{o.operateur} · {o.forfait.nom} · {o.numeroMasque} · {money(o.montantFcfa)}</p></div><div className="flex gap-2"><button onClick={()=>closeManual(o.id,'EXECUTED_MANUALLY')} className="border border-emerald-800 rounded-lg px-3 py-2">Exécutée manuellement</button><button onClick={()=>closeManual(o.id,'REFUNDED')} className="border border-slate-700 rounded-lg px-3 py-2">Remboursée</button></div></div></div>)}</div>:<p className="muted mt-4">Aucune commande à traiter manuellement.</p>}</section>
  <section className="card p-5"><h2 className="font-bold text-xl">6 · Wave</h2><div className="grid md:grid-cols-2 gap-4 mt-4"><div><h3 className="font-semibold">Marchands</h3><ul className="mt-2 space-y-2">{wave.marchands.map(m=><li className="rounded-lg bg-slate-950/60 p-3" key={m.id}>{m.nom} · {m.reference} · {m.actif?'actif':'inactif'}</li>)}</ul></div><div><h3 className="font-semibold">Notifications non rapprochées ({wave.nonRapprochees.length})</h3><ul className="mt-2 space-y-2">{wave.nonRapprochees.slice(0,10).map(n=><li className="rounded-lg border border-slate-800 p-3" key={n.id}><b>{n.reference}</b> · {money(n.montantFcfa)}<span className="muted block text-xs">{dt(n.dateReception)}</span></li>)}{!wave.nonRapprochees.length&&<li className="muted">Aucune notification non rapprochée.</li>}</ul></div></div></section>
  <section className="card p-5"><h2 className="font-bold text-xl">7 · Maintenance & sauvegardes</h2><div className="mt-4 grid md:grid-cols-3 gap-3"><div className="rounded-xl bg-slate-950/60 p-4"><p className="muted text-xs">État système</p><b>{maintenance?.etat??'—'}</b></div><div className="rounded-xl bg-slate-950/60 p-4"><p className="muted text-xs">Dernière sauvegarde</p><b>{maintenance?.sauvegarde?.derniere?dt(maintenance.sauvegarde.derniere):'Jamais'}</b><p className="muted text-xs">{maintenance?.sauvegarde?.statut}</p></div><div className="rounded-xl bg-slate-950/60 p-4"><p className="muted text-xs">Prochaine</p><b>{maintenance?.sauvegarde?.prochaine?dt(maintenance.sauvegarde.prochaine):'Planifiée Netlify'}</b></div></div><p className="muted text-sm mt-4">{maintenance?.message}</p></section>
 </main>
}
